apiVersion: v2
name: database-controller
description: Provisions roles, schemas and grants inside RDS and Aurora PostgreSQL
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - postgresql
  - rds
  - aurora
  - database
sources:
  - https://github.com/blairham/database-controller
