apiVersion: v2
name: database-access-controller
description: Provisions roles, schemas and grants inside RDS and Aurora PostgreSQL
type: application
version: 0.0.7
appVersion: "0.0.7"
keywords:
  - postgresql
  - rds
  - aurora
  - database
sources:
  - https://github.com/blairham/database-access-controller
